# Generated by Django 6.0.5 on 2026-07-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='tempo_estimado_minutos',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tempo_estimado',
            field=models.CharField(default='Não informado', help_text='Ex: 2 dias, 45 min, etc.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
