# Generated by Django 6.0.5 on 2026-07-05 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='marca',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default='Não informado', max_length=50),
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 5, 1, 57, 19, 443960, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default='Não informada', max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
