# Generated by Django 6.0.6 on 2026-07-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_remove_procedimento_tempo_estimado_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Ex: R$ 50 de óleo extra', null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='valor_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
