# Generated by Django 6.0.6 on 2026-07-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_cliente_ativo_veiculo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
